name: Generate README

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Generate README
      run: |
        pip install -r ./requirements.txt
        echo "Generating README files"
        python3 ./index.py
